import "@/app/styles/index.scss";
import Sidebar from "./components/sidebar";
import MobileHeader from "./components/headerMobile";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
          <MobileHeader />
        {children}
      </body>
    </html>
  );
}
