name: Deploy frontend webapp to S3

on:
  push:
    branches: ["main"]

  workflow_dispatch:
permissions:
  contents: read
  id-token: write

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    name: webapp-frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm config set legacy-peer-deps true
          npm install --legacy-peer-deps
          # npm install
          sudo npm install -g npm@latest

      - name: Build React Project with vite
        run: npm run build
        env:
          VITE_API: ${{ secrets.API }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: galadio-webapp
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    name: Deploy to S3
    steps:
      - name: Download artifacts (Docker images) from previous workflows
        uses: actions/download-artifact@v4
        with:
          name: galadio-webapp
          path: ./dist

      - name: "Configure AWS Credentials" 
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          audience: sts.amazonaws.com
          role-to-assume: ${{ secrets.ASSUME_ROLE_ARN }}
          role-session-name: Galadio
          mask-aws-account-id: true
          aws-region: us-east-1

      - name: Sync to S3
        id: deployment
        run: aws s3 sync public/ s3://${{ secrets.BUCKET_NAME }} --acl private

      - name: Invalidate Cloudfront Cache
        id: invalidation
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
